name: SEO Audit
on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://sairootmusic.com/
            https://sairootmusic.com/music?song=babylon-burn
          uploadArtifacts: true # Kamu bisa download hasil report-nya di tab Actions
          temporaryPublicStorage: true
