      - name: Bikin Sitemap Otomatis
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://sairootmusic.com/
          drop-github-md: true
          include-html-extension: false
          strip-extension: true

      - name: Sisipkan 28 Lagu SAI Roots
        run: |
          sed -i 's/\/index<\/loc>/<\/loc>/g' sitemap.xml
          
          SONGS="drama-klenik senandung-manis eksploitasi jurus-liar dari-jauh kasih-mengalun genjer-hijau timpang babylon-burn bayang-singgasana blaze-it-up evaluasi-lagi irama-hidup jamaican-sound ormas-tipu-tipu propaganda roots-medication skank-patrol reborn-riddim autopsi-mic salam-dari-timur mantra-malam magic-mushroom rastaman melayang-pelan tanah-hijau bbm-busuk kabur-saja-dulu"
          
          for s in $SONGS; do
            # Pastikan URL di sini SAMA PERSIS dengan domain di GSC
            sed -i '/<\/urlset>/i <url><loc>https://sairootmusic.com/music?song='$s'<\/loc><lastmod>'"$(date +%Y-%m-%d)"'</lastmod><priority>0.7</priority></url>' sitemap.xml
          done
